spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-db
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
